import test from 'node:test';
import assert from 'node:assert/strict';
import { Controller } from '../../.test-build/client/packages/terminal-client/src/controller.js';
class Socket{static OPEN=1;readyState=1;bufferedAmount=0;sent=[];onclose=null;send(m){this.sent.push(JSON.parse(m));}close(){this.readyState=3;queueMicrotask(()=>this.onclose?.());}}
globalThis.WebSocket=Socket;
const session=id=>({session_id:id,project_id:null,label:id,initial_cwd:'C:\\work',profile:'cmd',agent_epoch:'host',generation:1,state:'running',cols:120,rows:32,output_seq:'0',pid:1,process_created:'1',lease:{client_id:'device',connection_id:'connection',epoch:1,remaining_ms:15000}});
function ready(api){const c=new Controller(api);c.host={client_id:'device',agent_epoch:'host'};c.sessions=[session('a'),session('b')];c.connectionId='connection';c.connected=true;c.socket=new Socket();return c;}
test('PASTE-HTTP-01 actual payload is JSON body, not a nested Fetch RequestInit',async t=>{let call;const c=ready({async request(...args){call=args;}});t.after(()=>c.stop());await c.paste('a','한글'.repeat(5000),true);assert.equal(call[0],'/sessions/a/paste');assert.equal(call[2],'POST');assert.equal(call[1].text,'한글'.repeat(5000));assert.equal(call[1].append_enter,true);assert.equal(call[1].connection_id,'connection');assert.equal('body' in call[1],false);});
test('PASTE-HTTP-02 active transfer only blocks same session, Ctrl+C remains immediate',async t=>{let resolve;const c=ready({request(){return new Promise(r=>resolve=r);}});t.after(()=>c.stop());const pending=c.paste('a','pending',false);assert.throws(()=>c.input('a','x'));assert.throws(()=>c.binaryInput('a','x'));c.input('b','other project');c.input('a','\x03');assert.deepEqual(c.socket.sent.map(x=>[x.session_id,x.payload.text]),[['b','other project'],['a','\x03']]);resolve({});await pending;c.input('a','after');});
test('PASTE-HTTP-03 ambiguous error never retries uploaded command',async t=>{let calls=0;const c=ready({async request(){calls++;throw new Error('timeout');}});t.after(()=>c.stop());await assert.rejects(c.paste('a','dangerous command',true));assert.equal(calls,1);assert.match(c.notice,/자동 재전송하지 않습니다/);c.input('a','later');});
test('PASTE-HTTP-04 invalid pasted control sequence is not sent',async t=>{let calls=0;const c=ready({async request(){calls++;}});t.after(()=>c.stop());await assert.rejects(c.paste('a','\x1b[201~',true));assert.equal(calls,0);});
test('CONNECT-RACE-01 last connect wins and late old socket is closed',async t=>{const pending=[];const api={async authenticate(){},async request(path){return path==='/host'?{agent_epoch:'host',client_id:'device'}:[];},websocket(){return new Promise(r=>pending.push(r));}};const c=new Controller(api);t.after(()=>c.stop());const a=c.connect();await new Promise(r=>setImmediate(r));const b=c.connect();await new Promise(r=>setImmediate(r));assert.equal(pending.length,2);const fresh=new Socket();pending[1](fresh);await b;const stale=new Socket();pending[0](stale);await a;assert.equal(stale.readyState,3);assert.equal(c.socket,fresh);});

test('CONNECT-RACE-02 old socket events cannot overwrite new connection or lease',async t=>{
 const sockets=[];const api={async authenticate(){},async request(path){return path==='/host'?{agent_epoch:'host',client_id:'device'}:[session('a')];},async websocket(){const s=new Socket();sockets.push(s);return s;}};
 const c=new Controller(api);t.after(()=>c.stop());await c.connect();const old=sockets[0];await c.connect();const fresh=sockets[1];fresh.onmessage({data:JSON.stringify({type:'hello',protocol:1,agent_epoch:'host',connection_id:'fresh'})});
 old.onmessage({data:JSON.stringify({type:'hello',protocol:1,agent_epoch:'host',connection_id:'stale'})});old.onerror();old.onmessage({data:'invalid JSON'});
 assert.equal(c.connectionId,'fresh');assert.equal(c.connected,true);assert.equal(fresh.readyState,1);assert.equal(c.notice,'');
});
test('CONNECT-RACE-03 explicit stop clears cached writer identity and leases',t=>{const c=ready({});t.after(()=>c.stop());c.stop();assert.equal(c.connectionId,'');assert.equal(c.sessions.every(s=>s.lease===null),true);assert.equal(c.owns('a'),false);});

test('CONNECT-RACE-04 delayed old host lookup cannot replace a new epoch',async t=>{let oldHost;let hosts=0;const sockets=[];const api={async authenticate(){},request(path){if(path==='/host'){hosts++;if(hosts===1)return new Promise(r=>oldHost=r);return Promise.resolve({agent_epoch:'new-host',client_id:'device'});}return Promise.resolve([]);},async websocket(){const s=new Socket();sockets.push(s);return s;}};const c=new Controller(api);t.after(()=>c.stop());const first=c.connect();await new Promise(r=>setImmediate(r));await c.connect();oldHost({agent_epoch:'old-host',client_id:'device'});await first;assert.equal(c.host.agent_epoch,'new-host');assert.equal(sockets.length,1);});
test('CONNECT-RACE-05 obsolete session list cannot replace fresh list after reconnect',async t=>{let oldSessions;let lists=0;const api={async authenticate(){},request(path){if(path==='/host')return Promise.resolve({agent_epoch:'host',client_id:'device'});lists++;if(lists===1)return new Promise(r=>oldSessions=r);return Promise.resolve([session('fresh')]);},async websocket(){return new Socket();}};const c=new Controller(api);t.after(()=>c.stop());const first=c.connect();await new Promise(r=>setImmediate(r));await c.connect();oldSessions([session('old')]);await first;assert.deepEqual(c.sessions.map(s=>s.session_id),['fresh']);});
