import test from 'node:test';
import assert from 'node:assert/strict';
import { MediaClient } from '../../.test-build/client/packages/terminal-client/src/media-client.js';
const fingerprint=Array(32).fill('AB').join(':');
const sdp=`v=0\r\nm=video 9 UDP/TLS/RTP/SAVPF 96\r\na=fingerprint:sha-256 ${fingerprint}\r\na=rtpmap:96 H264/90000\r\n`;
const source={id:'source-a',generation:1,geometry_version:'1',label:'Approved app',kind:'window',control_allowed:true,rect:{left:0,top:0,width:1280,height:720}};
const flush=()=>new Promise(r=>setImmediate(r));
class Socket {readyState=1;bufferedAmount=0;sent=[];onmessage=null;onclose=null;onerror=null;send(s){this.sent.push(JSON.parse(s));}close(){this.readyState=3;queueMicrotask(()=>this.onclose?.({}));}message(m){this.onmessage?.({data:JSON.stringify(m)});}}
class Peer {static all=[];configuration;remoteDescription=null;localDescription=null;connectionState='new';closed=false;added=[];ontrack=null;onicecandidate=null;onconnectionstatechange=null;constructor(c){this.configuration=c;Peer.all.push(this);}async setRemoteDescription(s){this.remoteDescription=s;}async createAnswer(){return{type:'answer',sdp};}async setLocalDescription(s){this.localDescription=s;}async addIceCandidate(c){this.added.push(c);}close(){this.closed=true;this.connectionState='closed';this.onconnectionstatechange?.();}connected(){this.connectionState='connected';this.onconnectionstatechange?.();}}
class Video {srcObject=null;callbacks=new Map();next=0;async play(){}requestVideoFrameCallback(cb){const n=++this.next;this.callbacks.set(n,cb);return n;}cancelVideoFrameCallback(n){this.callbacks.delete(n);}present(at=performance.now()){const [id,cb]=this.callbacks.entries().next().value??[];assert.ok(cb,'frame callback registered');this.callbacks.delete(id);cb(at,{});}}
globalThis.RTCPeerConnection=Peer;
globalThis.MediaStream=class{constructor(tracks){this.tracks=tracks;}getTracks(){return this.tracks;}};
async function fixture(t){const socket=new Socket();const calls=[];const api={async websocket(channel,id){calls.push([channel,id]);return socket;},async wsTicket(channel,id){calls.push(['ticket',channel,id]);return'new-ticket';}};const video=new Video();const client=new MediaClient(api,video);t.after(()=>client.stop());await client.open(source);socket.message({type:'hello',protocol:1,source});await flush();return{client,socket,video,peer:Peer.all.at(-1),calls};}
function live(f){f.peer.connected();f.peer.ontrack({track:{kind:'video',stop(){},onended:null}});f.video.present();}
test('MEDIA-CLIENT-01 media ticket scoped to exact source, no STUN/TURN servers',async t=>{const f=await fixture(t);assert.deepEqual(f.calls,[['media','source-a']]);assert.deepEqual(f.peer.configuration.iceServers,[]);assert.equal(f.client.lease,null);});
test('MEDIA-CLIENT-02 no source or network heartbeat alone permits input',async t=>{const f=await fixture(t);assert.throws(()=>f.client.acquire());f.peer.connected();assert.throws(()=>f.client.acquire());assert.throws(()=>f.client.action({kind:'key',scan:28,extended:false,down:true}));assert.equal(f.socket.sent.some(x=>x.type==='input'),false);});
test('MEDIA-CLIENT-03 actual presented video is required before acquire, then inputs have monotonic sequence',async t=>{const f=await fixture(t);live(f);f.client.acquire();assert.equal(f.socket.sent.at(-1).type,'acquire');f.socket.message({type:'lease',lease_epoch:'7'});await flush();f.client.action({kind:'key',scan:28,extended:false,down:true});f.client.action({kind:'key',scan:28,extended:false,down:false});const inputs=f.socket.sent.filter(x=>x.type==='input');assert.deepEqual(inputs.map(x=>x.seq),['1','2']);assert.equal(inputs[0].generation,1);assert.equal(inputs[0].geometry_version,'1');});
test('MEDIA-CLIENT-04 stale presented frame revokes lease and rejects action',async t=>{const f=await fixture(t);live(f);f.socket.message({type:'lease',lease_epoch:'7'});await flush();f.video.present(performance.now()-1000);assert.throws(()=>f.client.action({kind:'move',x:0.5,y:0.5}));assert.equal(f.client.lease,null);assert.equal(f.socket.sent.some(x=>x.type==='release'),true);});
test('MEDIA-CLIENT-05 remote offer answered without embedded ICE candidates',async t=>{const f=await fixture(t);f.socket.message({type:'offer',sdp:sdp+'a=candidate:1 1 udp 1 192.168.0.1 50000 typ host\r\n'});await flush();const answer=f.socket.sent.find(x=>x.type==='answer');assert.ok(answer);assert.ok(!f.peer.remoteDescription.sdp.includes('candidate:'));assert.ok(!answer.sdp.includes('candidate:'));});
test('MEDIA-CLIENT-06 ICE received before remote description waits for offer',async t=>{const f=await fixture(t);f.socket.message({type:'ice',mline:0,candidate:'candidate:1 1 udp 1 100.70.0.2 50000 typ host'});await flush();assert.equal(f.peer.added.length,0);f.socket.message({type:'offer',sdp});await flush();assert.equal(f.peer.added.length,1);});
test('MEDIA-CLIENT-07 unapproved network candidate stops stream rather than dialing it',async t=>{const f=await fixture(t);f.socket.message({type:'ice',mline:0,candidate:'candidate:1 1 udp 1 192.168.0.3 50000 typ host'});await flush();assert.equal(f.peer.added.length,0);assert.equal(f.peer.closed,true);assert.equal(f.client.state,'failed');});
test('MEDIA-CLIENT-08 browser mDNS and public candidates are not signaled',async t=>{const f=await fixture(t);for(const ip of ['random.local','192.168.1.2','8.8.8.8'])f.peer.onicecandidate({candidate:{candidate:`candidate:1 1 udp 1 ${ip} 50001 typ host`,sdpMLineIndex:0}});assert.equal(f.socket.sent.some(x=>x.type==='ice'),false);f.peer.onicecandidate({candidate:{candidate:'candidate:1 1 udp 1 100.70.0.3 50001 typ host',sdpMLineIndex:0}});assert.equal(f.socket.sent.at(-1).type,'ice');});
test('MEDIA-CLIENT-09 video shutdown sends stop and closes only its media socket',async t=>{const f=await fixture(t);live(f);f.socket.message({type:'lease',lease_epoch:'1'});await flush();f.client.stop();await flush();assert.equal(f.peer.closed,true);assert.equal(f.socket.readyState,3);assert.equal(f.video.srcObject,null);assert.equal(f.video.callbacks.size,0);assert.deepEqual(f.socket.sent.slice(-2).map(x=>x.type),['release','stop']);assert.equal(f.calls.some(x=>x[0]==='control'||x[0]==='terminal'),false);});
test('MEDIA-CLIENT-10 stopped pending websocket does not resurrect video',async t=>{let resolve;const ws=new Socket();const api={websocket(){return new Promise(r=>resolve=r);}};const client=new MediaClient(api,new Video());t.after(()=>client.stop());const opening=client.open(source);client.stop();resolve(ws);await opening;assert.equal(ws.readyState,3);assert.equal(client.source,null);});
test('MEDIA-CLIENT-11 wrong source generation stops rather than taking control',async t=>{const f=await fixture(t);f.socket.message({type:'hello',protocol:1,source:{...source,generation:2}});await flush();assert.equal(f.client.state,'failed');assert.equal(f.client.lease,null);});
test('MEDIA-CLIENT-12 credentials refresh uses media-specific one-use ticket',async t=>{const f=await fixture(t);await f.client.refreshCredentials();assert.deepEqual(f.calls.at(-1),['ticket','media','source-a']);assert.deepEqual(f.socket.sent.at(-1),{type:'refresh_auth',ticket:'new-ticket'});});
test('MEDIA-CLIENT-13 backpressure cannot enqueue another remote click',async t=>{const f=await fixture(t);live(f);f.socket.message({type:'lease',lease_epoch:'1'});await flush();f.socket.bufferedAmount=70000;const n=f.socket.sent.length;assert.throws(()=>f.client.action({kind:'button',x:0,y:0,button:0,down:true}));assert.equal(f.socket.sent.length,n);});
test('MEDIA-CLIENT-14 invalid lease encoding is rejected',async t=>{const f=await fixture(t);f.socket.message({type:'lease',lease_epoch:9007199254740993});await flush();assert.equal(f.client.state,'failed');});

test('MEDIA-CLIENT-15 congestion closes only media so host can release injected keys',async t=>{const f=await fixture(t);live(f);f.socket.message({type:'lease',lease_epoch:'9'});await flush();f.socket.bufferedAmount=65537;assert.throws(()=>f.client.action({kind:'key',scan:28,extended:false,down:false}));assert.equal(f.client.lease,null);assert.equal(f.socket.readyState,3);assert.equal(f.peer.closed,true);assert.equal(f.client.state,'failed');});
