CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO schema_migrations(version) VALUES(1);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS preview_slots(origin TEXT PRIMARY KEY,project_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS devices(
 client_id TEXT PRIMARY KEY, public_key BLOB NOT NULL, label TEXT NOT NULL,
 scopes_json TEXT NOT NULL, approved_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 revoked INTEGER NOT NULL DEFAULT 0 CHECK(revoked IN(0,1))
);
CREATE TABLE IF NOT EXISTS projects(project_id TEXT PRIMARY KEY,canonical_cwd TEXT NOT NULL UNIQUE COLLATE NOCASE);
CREATE TABLE IF NOT EXISTS sessions(
 session_id TEXT PRIMARY KEY, metadata_json TEXT NOT NULL,
 lifecycle TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS audit_events(
 event_id INTEGER PRIMARY KEY AUTOINCREMENT, at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 client_id TEXT, action TEXT NOT NULL, resource_id TEXT
);
CREATE INDEX IF NOT EXISTS audit_at ON audit_events(at);
